waht_is_your_first_name = ("christian")
what_is_your_last_name = ("gordon")
what_is_your_favorate_anamie = ("ove the moon")
print(waht_is_your_first_name)
print(what_is_your_last_name)
print(what_is_your_favorate_anamie)